### ISSUE TITLE
make command 

### ISSUE THREAD

**Issue by kashifzr** [raisimTech/raisimExample#1]
I am trying to use this raisimExample but during make command the code below create problems

auto binaryPath = raisim::Path::setFromArgv(argv[0]);

**Comment by jhwangbo** [comment]
which OS? what is the error message? from which repo did you pull raisim?

**Comment by kashifzr** [comment]
I am using Ubuntu 18.04.5 LTS, Bionic and I use git clone to download from the repository of THIS example.

**Comment by kashifzr** [comment]
**Error Message** 

error: ‘raisim::Path’ has not been declared
   auto binaryPath = raisim::Path::setFromArgv(argv[0]);
                             ^~~~

**Comment by jhwangbo** [comment]
from which repo did you pull RAISIM? raisimTech/raisimlib?

**Comment by kashifzr** [comment]
I am using raisimLib from below repository 

https://github.com/leggedrobotics/raisimLib.git

**Comment by jhwangbo** [comment]
as the readme states, this repo is only for the newer version in raisimTech/raisimlib.

**Comment by kashifzr** [comment]
Oky, thanks

It requires RaiSim v1.0 (not released yet)
I thought as RaiSim v1.0 is not released yet may it work for old raisimLIb, WIthout RaiSim v1.0 does its works if downloaded and used from raisimTech/raisimlib?

**Comment by jhwangbo** [comment]
v1.0 is not fully ready but the version in raisimTech/raisimlib works fine with this repo. to use the new raisim, you have to get the activation key from here (http://raisim.com/sections/License.html#raisim-academic-license). Currently, we only offer activation keys for academics.

**Comment by kashifzr** [comment]
Thanks

**Comment by kashifzr** [comment]
# Once in the examples folder, type one of the following command:
# $ pip install -e .
# $ pip install --user -e .
# $ python setup.py install
# $ python setup.py install --home=<dir>

**Errors after executing pip install --user -e . Where I am doing wrong. All commands from Installation MANUAL works fine.** 

<pre>Obtaining file:///home/abc/new_raisim/raisimlib/raisimPy/examples
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File &quot;/usr/lib/python3/dist-packages/pip/download.py&quot;, line 421, in get_file_content
        with open(url, &apos;rb&apos;) as f:
    FileNotFoundError: [Errno 2] No such file or directory: &apos;requirements.txt&apos;
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
      File &quot;/home/abc/new_raisim/raisimlib/raisimPy/examples/setup.py&quot;, line 16, in &lt;module&gt;
        reqs = [str(ir.req) for ir in install_requires]
      File &quot;/home/abc/new_raisim/raisimlib/raisimPy/examples/setup.py&quot;, line 16, in &lt;listcomp&gt;
        reqs = [str(ir.req) for ir in install_requires]
      File &quot;/usr/lib/python3/dist-packages/pip/req/req_file.py&quot;, line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File &quot;/usr/lib/python3/dist-packages/pip/download.py&quot;, line 425, in get_file_content
        &apos;Could not open requirements file: %s&apos; % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: &apos;requirements.txt&apos;
    
</pre>

**Comment by jhwangbo** [comment]
Currently, only robots.py is working. You don't have to setup the examples. You can follow these steps

1. install raisimlib and raisimpy following this link http://raisim.com/sections/Installation.html
2. in your .bashrc, append install directory to PYTHONPATH. (e.g., export PYTHONPATH=$PYTHONPATH:<WHERE-YOU-INSTALLED-RAISIM>/lib)
3. go to raisimlib/raisimPy/examples and run robots.py

**Comment by kashifzr** [comment]
Thanks Jhwangbo
