### ISSUE TITLE
When running  ./raisimExample  error:Cannot find the license file

### ISSUE THREAD

**Issue by ClangWU** [raisimTech/raisimExample#3]
The whole error message is
Cannot find the license file \home\clang\Raisim_Platform\raisimExample\rsc
 
I  have already added the activation.raisim to the PATH ,but  it still doesn't work.

**Comment by jhwangbo** [comment]
It tries to find the activation key in the path you specified here (https://github.com/raisimTech/raisimExample/blob/a137128bd6363dc64d82f288c9d3b3f61235b915/main.cpp#L7)

It doesn't search in PATH. If no path is specified, it will try ``~/.raisim/activation.raisim``

**Comment by takayukikyk** [comment]
I tried to build raisimExample.
I got the key from email and saved `~/.raisim/activation.raisim`
But I couldn't successfully build it.

so I don't know why it doesn't work and hope this question can be solved.

**Comment by jhwangbo** [comment]
What is the error message?

**Comment by takayukikyk** [comment]
Here is the error message
**********************************************
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp: In function ‘int main(int, char**)’:
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:35: error: ‘PATH’ was not declared in this scope
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                   ^~~~
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:35: note: suggested alternative: ‘O_PATH’
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                   ^~~~
                                   O_PATH
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:40: error: ‘TO’ was not declared in this scope
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                        ^~
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:43: error: ‘THE’ was not declared in this scope
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                           ^~~
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:47: error: ‘ACTIVATION’ was not declared in this scope
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                               ^~~~~~~~~~
/home/USER_NAME/cmake_ws/src/raisimExample/main.cpp:7:58: error: ‘KEY’ was not declared in this scope
   raisim::World::setActivationKey(PATH-TO-THE-ACTIVATION-KEY);
                                                          ^~~
CMakeFiles/raisimExample.dir/build.make:75: recipe for target 'CMakeFiles/raisimExample.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/raisimExample.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/raisimExample.dir/all' failed
make[1]: *** [CMakeFiles/raisimExample.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
**********************************************

There's something I'd like to ask.
Is there a problem if the machine ID I submitted in RaiSim License Request Form is different from the machine ID listed on the key?

**Comment by jhwangbo** [comment]
If you saved the key in the right location, you can remove that line

**Comment by takayukikyk** [comment]
Thanks to you. I successfully build raismExample and generated the executable file.
but,I didn't execute `./raisimExample`

Here is the error message:
**************************
The license was issued to another machine 
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(maybe the machine ID I submitted in RaiSim License Request Form)
**************************
The above error message appears even though I have only one Linux PC that I am currently building my environment on.
I would appreciate any advice.

**Comment by jhwangbo** [comment]
What do you mean by maybe? is the machine id the same? can you run CheckMyMachineId again and see if you get the same id? and do you run it on Docker? Currently docker is not supported

**Comment by takayukikyk** [comment]
I didn't use  Docker.
The machine id displayed by the following command and the machine id displayed by the error message match.

`./Linux_raisimCheckMyMachine`

However, it is different from the MACHINE ID listed in the license key (activation.raisim) that you received from the email.

**Comment by jhwangbo** [comment]
How did you get the key for the machine "8B..."? that's not the key that I sent you. According to my sent box, your key starts with 87.

**Comment by takayukikyk** [comment]
Execute the command `./Linux_raisimCheckMyMachine` to get the key for the machine "8B".

It's exactly as you said.
The key I received starts with 87.

**Comment by jhwangbo** [comment]
You registered with a machine ID that starts with 87. Please register again with the key that you see.

The key is specific for the machine, user, and OS. If you changed any of these, you need to register again.

**Comment by takayukikyk** [comment]
Absolutely.
I registered the key starting with 8b in RaiSim License Request Form.

Thank you for your all help in advance.

**Comment by takayukikyk** [comment]
Thanks to you, I succeeded execute `./raisimExample` and example of raisimOgre successfully!
I would like to express my gratitude to you once again.

**Comment by jhwangbo** [comment]
My pleasure
