### ISSUE TITLE
When running ./raisimExample error:terminate called after throwing an instance of 'std::__ios_failure'

### ISSUE THREAD

**Issue by ClangWU** [raisimTech/raisimExample#4]
The whole message is:

**Comment by ClangWU** [comment]
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::underflow error reading the file: Is a directory
Aborted (core dumped)

**Comment by ClangWU** [comment]
It's the last step, I really want to make it.

**Comment by jhwangbo** [comment]
Please do not post issues like this. The error message already says what's wrong

**Comment by ClangWU** [comment]
Thanks jhwangbo
